##Foundamentals of Pytorch

In [1]:
!nvidia-smi # to check the detail of the GPU we have.

Wed Sep  6 10:44:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
print(torch.__version__)

2.0.1+cu118


**Tensor datatypes**

Default datatype in torch in float32 for float and int64 for int

In [3]:
type_32 = torch.tensor(2.0,
                       dtype=None,
                       device=None,
                       requires_grad=False)

print(type_32, type_32.dtype)

tensor(2.) torch.float32


In [4]:
type_16 = type_32.type(torch.float16)
type_16

tensor(2., dtype=torch.float16)

In [5]:
a = type_16 * type_32
print(a, a.dtype)

tensor(4.) torch.float32


In [6]:
type_32_vector = torch.tensor([1.0,2.0,3.0])
print(type_32_vector, type_32_vector.dtype)

tensor([1., 2., 3.]) torch.float32


In [7]:
type_16_vector = type_32_vector.type(torch.float16)
print(type_16_vector)

tensor([1., 2., 3.], dtype=torch.float16)


In [8]:
b = type_16_vector * type_32_vector
print(b, b.dtype)

tensor([1., 4., 9.]) torch.float32


**Introduction to the tensor**


In [9]:
scaler = torch.tensor(7)
scaler # type will be tensor-type

tensor(7)

In [10]:
scaler.ndim # scaler does not have a dimension

0

In [11]:
scaler.item() # to get the python int instead of tensor-type scaler

7

**Defining a vector**


In [12]:
vec = torch.tensor([1,2])
print(vec)
print('type:', type(vec)) # type will be torch.Tensor
print('dimension:', vec.ndim) # vector will have 1 dimension
print('shape:', vec.shape) # shape will show the num of elements

tensor([1, 2])
type: <class 'torch.Tensor'>
dimension: 1
shape: torch.Size([2])


**Defining the matrix/tensor**

*Imp: matrix and tensor must be defined with the capital letters*

In [13]:
# Two dimention tensor
MAT = torch.tensor([[1,2],
                    [3,4]])

In [14]:
print(MAT) # two dimension matrix
print('dimension:', MAT.ndim)
print('shape:', MAT.shape)

tensor([[1, 2],
        [3, 4]])
dimension: 2
shape: torch.Size([2, 2])


In [15]:
# accessing the values
print(MAT[0]) # first row, i.e [1,2]
print(MAT[1]) # second row, i.e [3,4]

tensor([1, 2])
tensor([3, 4])


In [16]:
print(MAT[0][1]) # first row's 2nd element, i.e. [2]

tensor(2)


*three dimension tensor*

torch.tensor([
  [ ],
  [ ],
  [ ],
])

In layman term: creating a three dim tensor is simply placing the multiple two_dim tensors inside a square bracket.

In [17]:
# 3 two_dim tensors inside a square bracket!
# all 3 two_dim tensors are of (2,3) shape
# so the overall shape of the below three_dim tensor will be [3,2,3].
THREEDIM = torch.tensor([
    [[1,2,3],[14,14,14]],

    [[11,22,33],[45,45,45]],

    [[111,222,333],[445,445,445]],
    ])
print(THREEDIM)
print('dimension:',THREEDIM.ndim)
print('shape:', THREEDIM.shape)

tensor([[[  1,   2,   3],
         [ 14,  14,  14]],

        [[ 11,  22,  33],
         [ 45,  45,  45]],

        [[111, 222, 333],
         [445, 445, 445]]])
dimension: 3
shape: torch.Size([3, 2, 3])


In [18]:
print('accessing 1st row of 1st 2_dim tensor:', THREEDIM[0][0])
print('accessing 1st row of 3rd 2_dim tensor:', THREEDIM[2][0])

accessing 1st row of 1st 2_dim tensor: tensor([1, 2, 3])
accessing 1st row of 3rd 2_dim tensor: tensor([111, 222, 333])


**Creating a random value tensor**

In [19]:
RANDOMTENSOR = torch.rand(5,2)
RANDOMTENSOR

tensor([[0.9790, 0.5290],
        [0.0454, 0.6622],
        [0.2242, 0.2417],
        [0.8215, 0.0984],
        [0.3624, 0.9261]])

We need to be familiar with the random tensor because neural network's weights are created similarly.

In [20]:
RANDOM_INT_TENSOR = torch.randint(low=1, high=5, size=(2,2))  # creating a random-valued tensor with values in-between 1 and 5 with shape 2,2
RANDOM_INT_TENSOR

tensor([[1, 3],
        [3, 4]])

**Tensor of all zeros or ones**

In [21]:
zeros = torch.zeros(size=(2,3))
ones = torch.ones(size=(2,3))
print(zeros,'\n')
print(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [22]:
print(zeros.dtype)

torch.float32


### Manipulating the tensors

In [23]:
# adding a number element-wise
sample = torch.tensor([1,2,3])
print(sample)

tensor([1, 2, 3])


In [24]:
add_5 = sample + 5
print(add_5)

tensor([6, 7, 8])


In [25]:
using_function = torch.add(sample, 5)
print(using_function)

tensor([6, 7, 8])


In [26]:
# element-wise multiplication
mul_5 = sample * 5
print(mul_5)

tensor([ 5, 10, 15])


In [27]:
using_function = torch.mul(sample, 5)
using_function

tensor([ 5, 10, 15])

In [28]:
# Matrix multiplication (dot product)
vec_1 = torch.tensor([1,2,3])
print(vec_1)

tensor([1, 2, 3])


In [29]:
vec_2 = torch.tensor([4,5,6])
print(vec_2)

tensor([4, 5, 6])


In [30]:
# (1*4 + 2*5 + 3*6) = 32
print(torch.matmul(vec_1, vec_2))

tensor(32)


Using the torch's built-in functions are fast.

In [31]:
%%time
val = 0
for i in range(len(vec_1)):
  val += vec_1[i] * vec_2[i]
print(val)


tensor(32)
CPU times: user 294 µs, sys: 57 µs, total: 351 µs
Wall time: 357 µs


In [32]:
%%time
print(torch.matmul(vec_1, vec_2))

tensor(32)
CPU times: user 216 µs, sys: 0 ns, total: 216 µs
Wall time: 221 µs


Min, Max, sum, mean functions

In [33]:
print(vec_1)

tensor([1, 2, 3])


In [34]:
# two ways
print(vec_1.min())
print(torch.min(vec_1))

tensor(1)
tensor(1)


In [35]:
print(vec_1.max())
print(torch.max(vec_1))

tensor(3)
tensor(3)


In [36]:
print(vec_1.sum())
print(torch.sum(vec_1))

tensor(6)
tensor(6)


In [37]:
print(vec_1.dtype)

torch.int64


In [38]:
print(torch.mean(vec_1)) # we can not calculate the mean with int64 or long type

RuntimeError: ignored

In [39]:
print(torch.mean(vec_1.type(torch.float32)))  # Changing the type to float 32 and calculating the mean.

tensor(2.)


##Reshaping, Stacking, Squeeze, Unsqueeze



In [40]:
vec = torch.arange(1.0, 16.0)
print(f"vec: {vec}")
print(f"\nShape of the vec: {vec.shape}")

vec: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15.])

Shape of the vec: torch.Size([15])


**reshaping**

In [41]:
reshaped_vec = vec.reshape(3,5)
print(f"Reshaped vec: {reshaped_vec}")
print(f"\nShape of the reshaped vec: {reshaped_vec.shape}")

Reshaped vec: tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])

Shape of the reshaped vec: torch.Size([3, 5])


**Squeeze**

In [42]:
vec = vec.reshape(1,15)
print(f"Shape of new vec: {vec.shape}")

Shape of new vec: torch.Size([1, 15])


In [43]:
#Squeeze will remove all of the single dimension from a tensor
squeezed_vec = vec.squeeze()
print(f"Squeezed vec: {squeezed_vec}")
print(f"\nShape of the squeezed vec: {squeezed_vec.shape}")

Squeezed vec: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15.])

Shape of the squeezed vec: torch.Size([15])


.squeeze has removed the single dimension

**unsqueeze**

In [44]:
# unsqueeze add the single dimension on the targetd axis
unsqueezed_vec = squeezed_vec.unsqueeze(dim=0)
print(f"Unsqueezed vec: {unsqueezed_vec}")
print(f"\n Shape of Unsqueezed vec: {unsqueezed_vec.shape}")

Unsqueezed vec: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15.]])

 Shape of Unsqueezed vec: torch.Size([1, 15])


In [45]:
# unsqueeze add the single dimension on the targetd axis
unsqueezed_vec = squeezed_vec.unsqueeze(dim=1)
print(f"Unsqueezed vec: {unsqueezed_vec}")
print(f"\n Shape of Unsqueezed vec: {unsqueezed_vec.shape}")

Unsqueezed vec: tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [13.],
        [14.],
        [15.]])

 Shape of Unsqueezed vec: torch.Size([15, 1])


**Permute: Used while working with the image data to swap the position from (height, width, channel) to (channel, height, width) or according to our need.**


In [46]:
vec = torch.rand(size=(5,5,3))
print(vec)
print(vec.shape)

tensor([[[0.4698, 0.2240, 0.0934],
         [0.3102, 0.5332, 0.4193],
         [0.9048, 0.0407, 0.0197],
         [0.7058, 0.6966, 0.5730],
         [0.0043, 0.3590, 0.3640]],

        [[0.1283, 0.4822, 0.8579],
         [0.0796, 0.7354, 0.1566],
         [0.5245, 0.9389, 0.5449],
         [0.0743, 0.2571, 0.1141],
         [0.7965, 0.9578, 0.5257]],

        [[0.2027, 0.4974, 0.5836],
         [0.1941, 0.2788, 0.4582],
         [0.6061, 0.5734, 0.1209],
         [0.8674, 0.0825, 0.6444],
         [0.0915, 0.8225, 0.5968]],

        [[0.9661, 0.7141, 0.9261],
         [0.5343, 0.9405, 0.0783],
         [0.5267, 0.6221, 0.7937],
         [0.7079, 0.8429, 0.0115],
         [0.9646, 0.6416, 0.3096]],

        [[0.4359, 0.5329, 0.7900],
         [0.5571, 0.1804, 0.9835],
         [0.8884, 0.0506, 0.2160],
         [0.6417, 0.1672, 0.1086],
         [0.8574, 0.3178, 0.7922]]])
torch.Size([5, 5, 3])


In [47]:
rearranged_shape = vec.permute(2,0,1)
print(rearranged_shape.shape)

torch.Size([3, 5, 5])


In [48]:
print(rearranged_shape)

tensor([[[0.4698, 0.3102, 0.9048, 0.7058, 0.0043],
         [0.1283, 0.0796, 0.5245, 0.0743, 0.7965],
         [0.2027, 0.1941, 0.6061, 0.8674, 0.0915],
         [0.9661, 0.5343, 0.5267, 0.7079, 0.9646],
         [0.4359, 0.5571, 0.8884, 0.6417, 0.8574]],

        [[0.2240, 0.5332, 0.0407, 0.6966, 0.3590],
         [0.4822, 0.7354, 0.9389, 0.2571, 0.9578],
         [0.4974, 0.2788, 0.5734, 0.0825, 0.8225],
         [0.7141, 0.9405, 0.6221, 0.8429, 0.6416],
         [0.5329, 0.1804, 0.0506, 0.1672, 0.3178]],

        [[0.0934, 0.4193, 0.0197, 0.5730, 0.3640],
         [0.8579, 0.1566, 0.5449, 0.1141, 0.5257],
         [0.5836, 0.4582, 0.1209, 0.6444, 0.5968],
         [0.9261, 0.0783, 0.7937, 0.0115, 0.3096],
         [0.7900, 0.9835, 0.2160, 0.1086, 0.7922]]])


## Tensor to numpy and numpy to tensor

In [58]:
import numpy as np

In [59]:
narray = np.arange(1,10)
print(narray)

[1 2 3 4 5 6 7 8 9]


In [61]:
# Numpy array to pytorch tensor
numpy_to_tensor = torch.from_numpy(narray)
print(numpy_to_tensor)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [62]:
dummy_tensor = torch.arange(1,10)
print(dummy_tensor)

tensor_to_numpy = dummy_tensor.numpy()
print(tensor_to_numpy)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
[1 2 3 4 5 6 7 8 9]


## GPU availability check


In [49]:
# below code will say whethere we have cuda (GPU access with pytorch)
torch.cuda.is_available()
# False == no cuda / GPU access
# True == support of cuda / GPU access

True

**Note!**
****
we should always have a device-agnostic test code so that if our model has to run on both CPU and GPU devices back and forth then our model won't break down.

In [50]:
# pytorch device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
# Using google colab, we can get a free GPU going to the runtime.

cuda


In [51]:
# giving GPU access to the tensor
dummy = torch.tensor([1,2,3,4,5])
print(dummy, dummy.device)
# By default, the device cpu

tensor([1, 2, 3, 4, 5]) cpu


In [52]:
dummy = dummy.to(device)
print(dummy, dummy.device)

tensor([1, 2, 3, 4, 5], device='cuda:0') cuda:0


**Note**
If we have a tensor with GPU, we cannot convert it into a numpy array. At first, it must be converted into a CPU.:

In [53]:
# example:
numpy_version = dummy.numpy()

TypeError: ignored

In [63]:
numpy_version = dummy.cpu().numpy()
print(numpy_version)

[1 2 3 4 5]
