<a href="https://colab.research.google.com/github/Shreejan-git/pytorch-complete-course/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
print(torch.__version__)

2.0.1+cu118


**Tensor datatypes**

Default datatype in torch in float32 for float and int64 for int

In [23]:
type_32 = torch.tensor(2.0,
                       dtype=None,
                       device=None,
                       requires_grad=False)

print(type_32, type_32.dtype)

tensor(2.) torch.float32


In [24]:
type_16 = type_32.type(torch.float16)
type_16

tensor(2., dtype=torch.float16)

In [27]:
a = type_16 * type_32
print(a, a.dtype)

tensor(4.) torch.float32


In [28]:
type_32_vector = torch.tensor([1.0,2.0,3.0])
print(type_32_vector, type_32_vector.dtype)

tensor([1., 2., 3.]) torch.float32


In [29]:
type_16_vector = type_32_vector.type(torch.float16)
print(type_16_vector)

tensor([1., 2., 3.], dtype=torch.float16)


In [30]:
b = type_16_vector * type_32_vector
print(b, b.dtype)

tensor([1., 4., 9.]) torch.float32


**Introduction to the tensor**


In [3]:
scaler = torch.tensor(7)
scaler # type will be tensor-type

tensor(7)

In [4]:
scaler.ndim # scaler does not have a dimension

0

In [5]:
scaler.item() # to get the python int instead of tensor-type scaler

7

**Defining a vector**


In [6]:
vec = torch.tensor([1,2])
print(vec)
print('type:', type(vec)) # type will be torch.Tensor
print('dimension:', vec.ndim) # vector will have 1 dimension
print('shape:', vec.shape) # shape will show the num of elements

tensor([1, 2])
type: <class 'torch.Tensor'>
dimension: 1
shape: torch.Size([2])


**Defining the matrix/tensor**

*Imp: matrix and tensor must be defined with the capital letters*

In [7]:
# Two dimention tensor
MAT = torch.tensor([[1,2],
                    [3,4]])

In [8]:
print(MAT) # two dimension matrix
print('dimension:', MAT.ndim)
print('shape:', MAT.shape)

tensor([[1, 2],
        [3, 4]])
dimension: 2
shape: torch.Size([2, 2])


In [9]:
# accessing the values
print(MAT[0]) # first row, i.e [1,2]
print(MAT[1]) # second row, i.e [3,4]

tensor([1, 2])
tensor([3, 4])


In [10]:
print(MAT[0][1]) # first row's 2nd element, i.e. [2]

tensor(2)


*three dimension tensor*

torch.tensor([
  [ ],
  [ ],
  [ ],
])

In layman term: creating a three dim tensor is simply placing the multiple two_dim tensors inside a square bracket.

In [11]:
# 3 two_dim tensors inside a square bracket!
# all 3 two_dim tensors are of (2,3) shape
# so the overall shape of the below three_dim tensor will be [3,2,3].
THREEDIM = torch.tensor([
    [[1,2,3],[14,14,14]],

    [[11,22,33],[45,45,45]],

    [[111,222,333],[445,445,445]],
    ])
print(THREEDIM)
print('dimension:',THREEDIM.ndim)
print('shape:', THREEDIM.shape)

tensor([[[  1,   2,   3],
         [ 14,  14,  14]],

        [[ 11,  22,  33],
         [ 45,  45,  45]],

        [[111, 222, 333],
         [445, 445, 445]]])
dimension: 3
shape: torch.Size([3, 2, 3])


In [12]:
print('accessing 1st row of 1st 2_dim tensor:', THREEDIM[0][0])
print('accessing 1st row of 3rd 2_dim tensor:', THREEDIM[2][0])

accessing 1st row of 1st 2_dim tensor: tensor([1, 2, 3])
accessing 1st row of 3rd 2_dim tensor: tensor([111, 222, 333])


**Creating a random value tensor**

In [13]:
RANDOMTENSOR = torch.rand(5,2)
RANDOMTENSOR

tensor([[0.9455, 0.7383],
        [0.6878, 0.1610],
        [0.9503, 0.2281],
        [0.4077, 0.5955],
        [0.5296, 0.1392]])

We need to be familiar with the random tensor because neural network's weights are created similarly.

In [14]:
RANDOM_INT_TENSOR = torch.randint(low=1, high=5, size=(2,2))  # creating a random-valued tensor with values in-between 1 and 5 with shape 2,2
RANDOM_INT_TENSOR

tensor([[4, 2],
        [1, 4]])

**Tensor of all zeros or ones**

In [15]:
zeros = torch.zeros(size=(2,3))
ones = torch.ones(size=(2,3))
print(zeros,'\n')
print(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [16]:
print(zeros.dtype)

torch.float32


### Manipulating the tensors