<a href="https://colab.research.google.com/github/Shreejan-git/pytorch-complete-course/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
print(torch.__version__)

2.0.1+cu118


**Tensor datatypes**

Default datatype in torch in float32 for float and int64 for int

In [3]:
type_32 = torch.tensor(2.0,
                       dtype=None,
                       device=None,
                       requires_grad=False)

print(type_32, type_32.dtype)

tensor(2.) torch.float32


In [4]:
type_16 = type_32.type(torch.float16)
type_16

tensor(2., dtype=torch.float16)

In [5]:
a = type_16 * type_32
print(a, a.dtype)

tensor(4.) torch.float32


In [6]:
type_32_vector = torch.tensor([1.0,2.0,3.0])
print(type_32_vector, type_32_vector.dtype)

tensor([1., 2., 3.]) torch.float32


In [7]:
type_16_vector = type_32_vector.type(torch.float16)
print(type_16_vector)

tensor([1., 2., 3.], dtype=torch.float16)


In [8]:
b = type_16_vector * type_32_vector
print(b, b.dtype)

tensor([1., 4., 9.]) torch.float32


**Introduction to the tensor**


In [9]:
scaler = torch.tensor(7)
scaler # type will be tensor-type

tensor(7)

In [10]:
scaler.ndim # scaler does not have a dimension

0

In [11]:
scaler.item() # to get the python int instead of tensor-type scaler

7

**Defining a vector**


In [12]:
vec = torch.tensor([1,2])
print(vec)
print('type:', type(vec)) # type will be torch.Tensor
print('dimension:', vec.ndim) # vector will have 1 dimension
print('shape:', vec.shape) # shape will show the num of elements

tensor([1, 2])
type: <class 'torch.Tensor'>
dimension: 1
shape: torch.Size([2])


**Defining the matrix/tensor**

*Imp: matrix and tensor must be defined with the capital letters*

In [13]:
# Two dimention tensor
MAT = torch.tensor([[1,2],
                    [3,4]])

In [14]:
print(MAT) # two dimension matrix
print('dimension:', MAT.ndim)
print('shape:', MAT.shape)

tensor([[1, 2],
        [3, 4]])
dimension: 2
shape: torch.Size([2, 2])


In [15]:
# accessing the values
print(MAT[0]) # first row, i.e [1,2]
print(MAT[1]) # second row, i.e [3,4]

tensor([1, 2])
tensor([3, 4])


In [16]:
print(MAT[0][1]) # first row's 2nd element, i.e. [2]

tensor(2)


*three dimension tensor*

torch.tensor([
  [ ],
  [ ],
  [ ],
])

In layman term: creating a three dim tensor is simply placing the multiple two_dim tensors inside a square bracket.

In [17]:
# 3 two_dim tensors inside a square bracket!
# all 3 two_dim tensors are of (2,3) shape
# so the overall shape of the below three_dim tensor will be [3,2,3].
THREEDIM = torch.tensor([
    [[1,2,3],[14,14,14]],

    [[11,22,33],[45,45,45]],

    [[111,222,333],[445,445,445]],
    ])
print(THREEDIM)
print('dimension:',THREEDIM.ndim)
print('shape:', THREEDIM.shape)

tensor([[[  1,   2,   3],
         [ 14,  14,  14]],

        [[ 11,  22,  33],
         [ 45,  45,  45]],

        [[111, 222, 333],
         [445, 445, 445]]])
dimension: 3
shape: torch.Size([3, 2, 3])


In [18]:
print('accessing 1st row of 1st 2_dim tensor:', THREEDIM[0][0])
print('accessing 1st row of 3rd 2_dim tensor:', THREEDIM[2][0])

accessing 1st row of 1st 2_dim tensor: tensor([1, 2, 3])
accessing 1st row of 3rd 2_dim tensor: tensor([111, 222, 333])


**Creating a random value tensor**

In [19]:
RANDOMTENSOR = torch.rand(5,2)
RANDOMTENSOR

tensor([[0.1207, 0.8634],
        [0.5946, 0.4036],
        [0.6168, 0.7756],
        [0.9632, 0.1509],
        [0.7117, 0.6069]])

We need to be familiar with the random tensor because neural network's weights are created similarly.

In [20]:
RANDOM_INT_TENSOR = torch.randint(low=1, high=5, size=(2,2))  # creating a random-valued tensor with values in-between 1 and 5 with shape 2,2
RANDOM_INT_TENSOR

tensor([[3, 1],
        [4, 2]])

**Tensor of all zeros or ones**

In [21]:
zeros = torch.zeros(size=(2,3))
ones = torch.ones(size=(2,3))
print(zeros,'\n')
print(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [22]:
print(zeros.dtype)

torch.float32


### Manipulating the tensors

In [23]:
# adding a number element-wise
sample = torch.tensor([1,2,3])
print(sample)

tensor([1, 2, 3])


In [24]:
add_5 = sample + 5
print(add_5)

tensor([6, 7, 8])


In [25]:
using_function = torch.add(sample, 5)
print(using_function)

tensor([6, 7, 8])


In [26]:
# element-wise multiplication
mul_5 = sample * 5
print(mul_5)

tensor([ 5, 10, 15])


In [27]:
using_function = torch.mul(sample, 5)
using_function

tensor([ 5, 10, 15])

In [28]:
# Matrix multiplication (dot product)
vec_1 = torch.tensor([1,2,3])
print(vec_1)

tensor([1, 2, 3])


In [29]:
vec_2 = torch.tensor([4,5,6])
print(vec_2)

tensor([4, 5, 6])


In [30]:
# (1*4 + 2*5 + 3*6) = 32
print(torch.matmul(vec_1, vec_2))

tensor(32)


Using the torch's built-in functions are fast.

In [51]:
%%time
val = 0
for i in range(len(vec_1)):
  val += vec_1[i] * vec_2[i]
print(val)


tensor(32)
CPU times: user 2.19 ms, sys: 0 ns, total: 2.19 ms
Wall time: 2.15 ms


In [32]:
%%time
print(torch.matmul(vec_1, vec_2))

tensor(32)
CPU times: user 418 µs, sys: 0 ns, total: 418 µs
Wall time: 425 µs


Min, Max, sum, mean functions

In [38]:
print(vec_1)

tensor([1, 2, 3])


In [39]:
# two ways
print(vec_1.min())
print(torch.min(vec_1))

tensor(1)
tensor(1)


In [40]:
print(vec_1.max())
print(torch.max(vec_1))

tensor(3)
tensor(3)


In [45]:
print(vec_1.sum())
print(torch.sum(vec_1))

tensor(6)
tensor(6)


In [46]:
print(vec_1.dtype)

torch.int64


In [47]:
print(torch.mean(vec_1)) # we can not calculate the mean with int64 or long type

RuntimeError: ignored

In [49]:
print(torch.mean(vec_1.type(torch.float32)))  # Changing the type to float 32 and calculating the mean.

tensor(2.)


##Reshaping, Stacking, Squeeze, Unsqueeze



In [58]:
vec = torch.arange(1.0, 16.0)
print(f"vec: {vec}")
print(f"\nShape of the vec: {vec.shape}")

vec: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15.])

Shape of the vec: torch.Size([15])


**reshaping**

In [60]:
reshaped_vec = vec.reshape(3,5)
print(f"Reshaped vec: {reshaped_vec}")
print(f"\nShape of the reshaped vec: {reshaped_vec.shape}")

Reshaped vec: tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])

Shape of the reshaped vec: torch.Size([3, 5])


**Squeeze**

In [62]:
vec = vec.reshape(1,15)
print(f"Shape of new vec: {vec.shape}")

Shape of new vec: torch.Size([1, 15])


In [65]:
#Squeeze will remove all of the single dimension from a tensor
squeezed_vec = vec.squeeze()
print(f"Squeezed vec: {squeezed_vec}")
print(f"\nShape of the squeezed vec: {squeezed_vec.shape}")

Squeezed vec: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15.])

Shape of the squeezed vec: torch.Size([15])


.squeeze has removed the single dimension

**unsqueeze**

In [66]:
# unsqueeze add the single dimension on the targetd axis
unsqueezed_vec = squeezed_vec.unsqueeze(dim=0)
print(f"Unsqueezed vec: {unsqueezed_vec}")
print(f"\n Shape of Unsqueezed vec: {unsqueezed_vec.shape}")

Unsqueezed vec: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15.]])

 Shape of Unsqueezed vec: torch.Size([1, 15])


In [67]:
# unsqueeze add the single dimension on the targetd axis
unsqueezed_vec = squeezed_vec.unsqueeze(dim=1)
print(f"Unsqueezed vec: {unsqueezed_vec}")
print(f"\n Shape of Unsqueezed vec: {unsqueezed_vec.shape}")

Unsqueezed vec: tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [13.],
        [14.],
        [15.]])

 Shape of Unsqueezed vec: torch.Size([15, 1])


**Permute: Used while working with the image data to swap the position from (height, width, channel) to (channel, height, width) or according to our need.**


In [69]:
vec = torch.rand(size=(5,5,3))
print(vec)
print(vec.shape)

tensor([[[0.5576, 0.6103, 0.2587],
         [0.1394, 0.6890, 0.8322],
         [0.6100, 0.1364, 0.2849],
         [0.4934, 0.0841, 0.3674],
         [0.3962, 0.4889, 0.2468]],

        [[0.6274, 0.6244, 0.7529],
         [0.8183, 0.3926, 0.4651],
         [0.5436, 0.0445, 0.7933],
         [0.4900, 0.4587, 0.8140],
         [0.0855, 0.7494, 0.6559]],

        [[0.4266, 0.8651, 0.2785],
         [0.5638, 0.3827, 0.3116],
         [0.8876, 0.9856, 0.5459],
         [0.4283, 0.9644, 0.2854],
         [0.2213, 0.7340, 0.3215]],

        [[0.8021, 0.7210, 0.1461],
         [0.3282, 0.5365, 0.8634],
         [0.8968, 0.6211, 0.0141],
         [0.0989, 0.8517, 0.7257],
         [0.6526, 0.0372, 0.1969]],

        [[0.1163, 0.3096, 0.5600],
         [0.8920, 0.3508, 0.0873],
         [0.7828, 0.3488, 0.1955],
         [0.6666, 0.1189, 0.6886],
         [0.0106, 0.9191, 0.1753]]])
torch.Size([5, 5, 3])


In [70]:
rearranged_shape = vec.permute(2,0,1)
print(rearranged_shape.shape)

torch.Size([3, 5, 5])


In [72]:
print(rearranged_shape)

tensor([[[0.5576, 0.1394, 0.6100, 0.4934, 0.3962],
         [0.6274, 0.8183, 0.5436, 0.4900, 0.0855],
         [0.4266, 0.5638, 0.8876, 0.4283, 0.2213],
         [0.8021, 0.3282, 0.8968, 0.0989, 0.6526],
         [0.1163, 0.8920, 0.7828, 0.6666, 0.0106]],

        [[0.6103, 0.6890, 0.1364, 0.0841, 0.4889],
         [0.6244, 0.3926, 0.0445, 0.4587, 0.7494],
         [0.8651, 0.3827, 0.9856, 0.9644, 0.7340],
         [0.7210, 0.5365, 0.6211, 0.8517, 0.0372],
         [0.3096, 0.3508, 0.3488, 0.1189, 0.9191]],

        [[0.2587, 0.8322, 0.2849, 0.3674, 0.2468],
         [0.7529, 0.4651, 0.7933, 0.8140, 0.6559],
         [0.2785, 0.3116, 0.5459, 0.2854, 0.3215],
         [0.1461, 0.8634, 0.0141, 0.7257, 0.1969],
         [0.5600, 0.0873, 0.1955, 0.6886, 0.1753]]])
